identity:
  cert: "./credentials/cert.pem"
  privateKey: "./credentials/priv_sk"
  mspId: "Org1MSP"

connection:
  tls: true
  tlsCert: "./credentials/ca.crt"
  peerEndpoint: "localhost:7051"
  gatewayPeer: "peer0.org1.example.com"
